---
version: "3.1"

services:
  vault:
    image: hashicorp/vault:${VAULT_VERSION}
    command: "/usr/local/bin/docker-entrypoint.sh server -dev"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200

  ca:
    build:
      context: ca/
      args:
        VAULT_VERSION: "${VAULT_VERSION}"
    hostname: ca
    environment:
      - VAULT_ADDR=http://vault:8200

  db:
    build:
      context: server/
      args:
        VAULT_VERSION: "${VAULT_VERSION}"
    environment:
      - VAULT_ADDR=http://vault:8200
      - SERVERNAME=db
    hostname: db
    cap_add:
      - SYS_CHROOT

  web:
    build:
      context: server/
      args:
        VAULT_VERSION: "${VAULT_VERSION}"
    environment:
      - VAULT_ADDR=http://vault:8200
      - SERVERNAME=web
    hostname: web
    cap_add:
      - SYS_CHROOT
